TodosProject/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

handler404 = 'todos_app.views.not_found_404'
handler500 = 'todos_app.views.internal_error_500'

urlpatterns = patterns('',
	url(r'^todos/', include('todos_app.urls',namespace='todos')),
	# Examples:
    # url(r'^$', 'TodosProject.views.home', name='home'),
    # url(r'^TodosProject/', include('TodosProject.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

todos_app/urls.py
from django.conf.urls import patterns, url
from todos_app import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='Index'),
    url(r'^(?P<todo_id>\d+)/$', views.detail, name='Detail'),
    url(r'^update/(?P<todo_id>\d+)/$', views.update, name='Update'),
    url(r'^save$', views.save, name='Save-task'),
)

todos_app/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=50)
    active = models.IntegerField(default=1)
    creation_date = models.DateTimeField()
    
    def __unicode__(self):
        return self.username

class Task(models.Model):
    task = models.CharField(max_length=80)
    creation_date = models.DateTimeField()
    date = models.DateTimeField('date')
    active = models.IntegerField(default=1)
    id_user = models.ForeignKey(User)

    def __unicode__(self):
        return self.task

todos_app/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.template import Context, loader
from todos_app.models import Task
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.core.urlresolvers import reverse
import json

def index(request):
    latest_todos = Task.objects.order_by('-creation_date')[:5]
    template = loader.get_template('tasks/index.html')
    context = Context({
        'latest_todos': latest_todos,
    })
    return HttpResponse(template.render(context))

def detail(request, todo_id):
	try:
            task = Task.objects.get(pk=todo_id)
    	except Task.DoesNotExist:
        	raise Http404
   	return render(request, 'tasks/detail.html', {'task': task})

def update(request, todo_id):
    try:
        task = Task.objects.get(pk=todo_id)
    except Task.DoesNotExist:
        raise Http404
    return render(request, 'tasks/update.html', {'task': task})
        
def save(request):
    p = get_object_or_404(Task, pk=request.POST['id'])
    p.task = request.POST['task']
    p.save(update_fields=['task'])
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    result = [p.id]
    return HttpResponse(json.dumps(result), content_type="application/json")

def not_found_404(request, template_name='system/not_found.html'):
    return render(request, template_name,{'request_path': request.path})

def internal_error_500(request,template_name='system/internal_error.html'):
	return render(request, template_name)

todos_app/templates/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}Doit {% endblock %}</title>	
    <link rel="stylesheet" type="text/css" href="{% static 'todos/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'todos/css/style.css' %}" />
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Doit</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div id="content" class="container">
    	<div class="ui-wall">
    	{% spaceless %}
        {% block content %}{% endblock %}
        {% endspaceless %}
        </div>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{% static 'todos/js/bootstrap.min.js' %}"></script>
</body>
</html>

todos_app/templates/system/internal_error.html
500 Error found....I'm sorry...

todos_app/templates/system/not_found.html
404 Error found!!...I'm sorry...the url: {{ request_path }} doesn't exist.

todos_app/templates/tasks/detail.html
{% extends "layout/base.html" %}
{% block content %}
{{ task }}
{% endblock %}

todos_app/templates/tasks/index.html
{% extends "layout/base.html" %}
{% block content %}
{% if latest_todos %}
	<h6>My first to-do list.</h6>
    <ul>
    {% for task in latest_todos %}
        <li>{{ forloop.counter }}. {{ task.task }} <a href="{% url 'todos:Detail' task.id %}" class="doit-green">Ver tarea</a> / <a href="{% url 'todos:Update' task.id %}" class="doit-green">Editar tarea</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No tasks are available.</p>
{% endif %}
{% endblock %}

todos_app/templates/tasks/save.html
{{ saved }}

todos_app/templates/tasks/update.html
{% extends "layout/base.html" %}
{% block content %}
<h1>{{ task.task }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'todos:Save-task' %}" method="post">
{% csrf_token %}
	<label for="ui-taskInput">Titulo:</label><br />
	<input type="text" name="task" id="ui-taskInput" value="{{ task.task }}" />
	<input type="hidden" name="id" value="{{ task.id }}">
	<input type="submit" value="Vote" class="btn btn-success" />
</form>
{% endblock %}